### ISSUE TITLE
How to query/load contact from SQL database?

### ISSUE THREAD

**Issue by sig100** [twisted/ldaptor#154]
I searched for sample code of ldaptor and found this website:
https://ldaptor.readthedocs.io/en/latest/cookbook/servers.html .It only provides with an emample of pre-load DIT from the python code. I think very few people would hard code contact information in script, since there are often hundreds or more employees in a company , and guys enter and leave frequently.
Could anybody offer me some help how to conduct a SQL query when receiving a LDAP query?

**Comment by GrayAn** [comment]
Hi @sig100 !

Here is a sample server which uses [SQLAlchemy](https://www.sqlalchemy.org/) to create a temporary sqlite database with "employee" table. `LDAPServerFactory` receives data from the database and serves it to the LDAP clients.

In this implementation `LDAPServerFactory` receives data only once (on server start). Method `reload_tree` can be called to force it to reload data.

```python
import sys

from ldaptor.inmemory import ReadOnlyInMemoryLDAPEntry
from ldaptor.interfaces import IConnectedLDAPEntry
from ldaptor.protocols.ldap.ldapserver import LDAPServer

from sqlalchemy import Column, Integer, String, create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session

from twisted.internet import reactor
from twisted.internet.protocol import ServerFactory
from twisted.python.components import registerAdapter
from twisted.python import log

Base = declarative_base()


class LDAPServerFactory(ServerFactory):
    protocol = LDAPServer

    def __init__(self, db_engine):
        self.db_engine = db_engine
        self.tree = None
        self.reload_tree()

    def reload_tree(self):
        """
        Building LDAP tree.
        Call this method if you need to reload data from the database.
        """
        com_tree = ReadOnlyInMemoryLDAPEntry('dc=com')
        example_tree = com_tree.addChild('dc=example', {})
        users_tree = example_tree.addChild('ou=users', {})

        db_session = Session(self.db_engine)

        for employee in db_session.query(Employee):
            users_tree.addChild('uid={}'.format(employee.uid), {
                'uid': [employee.uid],
                'givenName': [employee.first_name],
                'sn': [employee.last_name],
                'email': [employee.email],
            })

        db_session.close()

        self.tree = com_tree


class Employee(Base):
    __tablename__ = 'employee'

    id = Column(Integer, primary_key=True)
    uid = Column(String(255), nullable=False)
    first_name = Column(String(255), nullable=False)
    last_name = Column(String(255), nullable=False)
    email = Column(String(255), nullable=False)


def create_db():
    """Creating a database with a table of employees and a couple of rows"""
    db_engine = create_engine('sqlite://')
    Base.metadata.bind = db_engine
    Employee.__table__.create()

    db_session = Session(db_engine)

    employee1 = Employee()
    employee1.uid = 'f.example'
    employee1.first_name = 'First'
    employee1.last_name = 'Example'
    employee1.email = 'first@example.com'
    db_session.add(employee1)

    employee2 = Employee()
    employee2.uid = 's.example'
    employee2.first_name = 'Second'
    employee2.last_name = 'Example'
    employee2.email = 'second@example.com'
    db_session.add(employee2)

    db_session.commit()
    db_session.close()

    return db_engine


if __name__ == '__main__':
    engine = create_db()

    log.startLogging(sys.stderr)

    registerAdapter(lambda x: x.tree, LDAPServerFactory, IConnectedLDAPEntry)
    factory = LDAPServerFactory(engine)
    reactor.listenTCP(8080, factory)
    reactor.run()
```

**Comment by sig100** [comment]
> ```python
> sqlalchemy 
> ```

Thank you GrayAn, your sample code is of great help.

**Comment by GrayAn** [comment]
Thanks! I am going to move this piece of code to the examples.

**Comment by TencentSZ** [comment]
I found a problem. In this example https://ldaptor.readthedocs.io/en/latest/quickstart.html#ldap-server-quick-start, I can load the LDAP tree in JXplorer like this

![图片](https://user-images.githubusercontent.com/52615214/64687552-4d29c000-d4bd-11e9-8ae5-5fe12fe5f697.png)

While in this example above, users are not displayed under the organization.
![图片](https://user-images.githubusercontent.com/52615214/64687642-75b1ba00-d4bd-11e9-89bc-db0ce0d68c7c.png)

**Comment by TencentSZ** [comment]
2019-09-11 18:09:14+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 142, in _gotChildren
            children.pop().subtree(callback)
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 143, in subtree
            d.addCallback(_gotChildren, callback)
          File "d:\code_python\LDAP\twisted\internet\defer.py", line 322, in addCallback
            callbackKeywords=kw)
          File "d:\code_python\LDAP\twisted\internet\defer.py", line 311, in addCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "d:\code_python\LDAP\twisted\internet\defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 142, in _gotChildren
            children.pop().subtree(callback)
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 137, in subtree
            callback(self)
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 291, in _tryMatch
            if entry.match(filterObject):
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 214, in match
            if not self.match(filt):
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 219, in match
            if self.match(filt):
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 171, in match
            for x in possibleMatches
          File "d:\code_python\LDAP\ldaptor\entryhelpers.py", line 172, in <listcomp>
            if x.lower().startswith(filter.substrings[0].value.lower())
        builtins.TypeError: startswith first arg must be str or a tuple of str, not bytes
