### ISSUE TITLE
BerOctetString Repr

### ISSUE THREAD

**Issue by xdesai** [twisted/ldaptor#167]
Hey ldaptor team we got another one for ya!

As is seen in PR https://github.com/twisted/ldaptor/pull/164, calling repr() on a BEROctetString results in an exception when the value of the BEROctetString is not utf-8 encoded bytes. In practice, LDAPBindResponse_serverSaslCreds has non-utf-8 bytes as demonstrated by the PR, and it turns out that LDAPMessages may have non-utf-8 bytes as well. One specific example is the controls used during a paged search. The cookie part of the controls is not utf-8 and therefore also leads to the same type of exception when an LDAPMessage with one of these cookies is being repr()’d. 

The root of both of this issue and that PR is that repr_converter can’t handle bytes that aren’t utf-8 encoded so `BEROctetString.__repr__` can often lead to an exception in real-world application. 

```
from ldaptor.protocols.pureber import BEROctetString
# A real cookie from a search against AD
cookie = b'\xa3\x02\x00\x00'
octet_string = BEROctetString(cookie)

# results in an exception being raised
repr(octet_string)
```
It seems that either:
`BEROctetString.__repr__` should be updated to not use `repr_converter` to account for its value not necessarily being utf-8 encoded bytes.
OR `repr_converter` should not assume that it can always decode bytes as utf-8 and should fail gracefully if it can’t.

Additionally, if one the above changes were to be implemented (or something similar) then the changes in the PR listed above wouldn’t be necessary. 

Do you all have any preference on where the change for this should occur? On our fork personally we're rolling with a change to repr_converter to basically catch a UnicodeError and then not raise if the bytes can't be decoded but instead just letting the bytes get repr()'d and printed.

Whichever one sounds better to you all let us know and we'll likely be able to get a PR up for it.

**Comment by graingert** [comment]
@xdesai fixed in https://github.com/twisted/ldaptor/pull/198
