### ISSUE TITLE
enable PR builds for readthedocs

### ISSUE THREAD

**Issue by graingert** [twisted/ldaptor#182]
@hynek @psi29a can you enable PR builds for https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html https://readthedocs.org/projects/ldaptor/ please?

can you also export the current settings as a .readthedocs.yml  file?

**Comment by graingert** [comment]
That PR wasn't ready - you need to enable the webhooks first

**Comment by graingert** [comment]
@psi29a do you have permissions to create webhooks in this repository?

**Comment by psi29a** [comment]
I do have access to create webhooks (as admin here) but I need you to tell me the steps. I'm kinda acting as maintenance mode guy at the moment.

**Comment by psi29a** [comment]
"Build pull requests for this project" is already enabled for example.

**Comment by psi29a** [comment]
I do not see anywhere where I can export a .readthedocs.yml , just that it can use one...

**Comment by graingert** [comment]
@psi29a I posted the instructions to @adiroiban in IRC, https://twistedmatrix.com/trac/ticket/9980#comment:1 instructions for twisted exist here

**Comment by graingert** [comment]
>  I'm kinda acting as maintenance mode guy at the moment.

I currently have guest access to ldaptor and so can merge PRs when they are approved. Please review and approve PRs you approve of, but I'd ask you not to merge them so I can do so in the correct order.

If you have the time please get in contact with me on IRC so I can talk you through configuring readthedocs and creating a v20.0 and v20.1 release
