### ISSUE TITLE
replace PyCrypto usage with PyCA's Cryptography

### ISSUE THREAD

**Issue by glyph** [twisted/ldaptor#2]

**Comment by schlenk** [comment]
ldaptor seems to use only DES (for the crappy LanManager Password Hashes). cryptography does not provide that cipher. So guess this cannot be fixed, unless cryptography provides DES or LanManager hashes are extinct.

**Comment by reaperhulk** [comment]
3DES uses an "encrypt decrypt encrypt" model (EDE) so you can do single DES encryption and decryption with pyca/cryptography by doing the following:

```python
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.backends import default_backend
3des_key = des_key * 3 # just concat the key 3x
cipher = Cipher(algorithms.3DES(3des_key), modes.ECB(), backend=default_backend())
encryptor = cipher.encryptor()
# not using padding here so you'll need to make sure your input is a multiple of block size or else add padding
ct = encryptor.update(b"encrypt!") + encryptor.finalize()
```

This will work (albeit 3x as slow as single DES).

Ideally you'd just drop LM support though as it's beyond ancient.

**Comment by glyph** [comment]
Beyond ancient *and* completely insecure; this is an interoperability measure, not a security measure.  If it is at all avoidable it would be better just to drop it.

**Comment by simo5** [comment]
If you need this just for LanManager hashes, just forget about it, LanManager hashes are comepltely useless for compatibility unless you are catering for 25 year old machines.
Anything that can use LanManager today has it probably disabled and allows only NTLM (using NT hashes) thorugh instead. NT hashes are nothing great bu they don't use DES, only RC4 and MD4.
Just drop LM it's dead.

**Comment by graingert** [comment]
@glyph any update on this?

**Comment by glyph** [comment]
It should still happen, for sure! I don’t really work on ldaptor, though.

**Comment by psi29a** [comment]
@graingert thanks!
