### ISSUE TITLE
release 20.1.1 ?

### ISSUE THREAD

**Issue by graingert** [twisted/ldaptor#200]
with the new reprs

**Comment by adiroiban** [comment]
As you wish :)

At this point, I think that anyone can propose a release just by create a PR.

Maybe the docs can be in PR https://github.com/twisted/ldaptor/pull/192 to inform that ldaptor is relaxed in terms of a release, and anyone can trigger a release  at any time.

And to trigger a release, you just create a PR, without an extra issue :)
