### ISSUE TITLE
ldapsearch against ldaptor always returns all attributes

### ISSUE THREAD

**Issue by the2nd** [twisted/ldaptor#38]
Hi,
if i do an ldapsearch agains ldaptor which requests just one (or some) attributes ldaptor seems to always return the complete ldif of the found object. Using the same seach against openldap only the "dn" and the requested attributes are returned.

You should be able to reproduce with the following steps:

Try ldapsearch which requests only specific attribute(s) with ldaptor:
1. run ldaptest.py
2. on second console run ldapsearch command that requests only "uid" attribute: ldapsearch -H ldap://localhost:8080 -b "dc=de" -w afdg -x uid
3. the ldif returned from ldapsearch contains all object attributes!

Try ldapsearch which requests only specific attribute(s) with openldap:
1. copy slapd.conf to /etc/openldap (or whatever directory your distribution uses)
2. import ldap tree from ldaptor: ldapsearch -H ldap://localhost:8080 -b "dc=de" -w afdg -x | slapadd -l /dev/stdin
3. start slapd (e.g. /etc/init.d/slapd start)
4. run ldapsearch command that requests only "uid" attribute: ldapsearch -H ldap://localhost -b "dc=de" -D 'cn=manager,dc=example,dc=de' -w root -x uid
5. the ldif returned from ldapsearch contains only "dn" and "uid" attributes

ldaptor.py: https://bpaste.net/show/3f5174d8ec15
slapd.conf: https://bpaste.net/show/c334ec415850

reference: http://twistedmatrix.com/pipermail/twisted-python/2015-May/029447.html

**Comment by psi29a** [comment]
@the2nd Does https://github.com/twisted/ldaptor/pull/40 fix your problem? :)

**Comment by the2nd** [comment]
Yes #40 fixes the issue. Thanks a lot! :)
