### ISSUE TITLE
How to handle authentication without user password in ldap tree

### ISSUE THREAD

**Issue by the2nd** [twisted/ldaptor#39]
i'm trying to implement an read-only ldap server for OTPme (https://www.otpme.org/) using ldaptor and as OTPme focus on OTPs i dont want to add a static password (attribute) to the ldap tree. instead it would be great to get the username/OTP from ldaptor for verification.

is there any interface in ldaptor for this?

reference: http://twistedmatrix.com/pipermail/twisted-python/2015-May/029447.html

**Comment by the2nd** [comment]
ok, i figured it out myself. :)

for everyone who wants to do the same. you just have to add a bind() method to your "db" class. an example bind() method can be found in entry.py (BaseLDAPEntry()).

**Comment by psi29a** [comment]
I take it you have looked at the examples?
https://ldaptor.readthedocs.org/en/stable/

There aren't many there, but we could always do for more.

**Comment by adiroiban** [comment]
I think that this can be closed.

The "acting" code is here :

https://github.com/twisted/ldaptor/blob/cf23b3eab46a41414efd331e3f753828890a4bd2/ldaptor/protocols/ldap/ldapserver.py#L169

The server is searching for the entry and then calling the `bind` method on that LDAP entry.

Thanks for the info
