### ISSUE TITLE
LGPL Headers in various ldaptor/protocols/ldap/ files but LICENSE states different License

### ISSUE THREAD

**Issue by schlenk** [twisted/ldaptor#48]
Not sure if this is intended, looks like a leftover from the License change.

@tv42  seems to be the original author and relicensed ldaptor according to the history in LICENSE, but there are a bunch of files in ldaptor/protocols/ldap that still have the LGPL headers (e.g ldapclient.py)

So what is the license status of those files?

**Comment by psi29a** [comment]
tv42 re-licensed everything to MIT, so these are remnants that still need to be taken care of.

Thanks for spotting this!

**Comment by tv42** [comment]
I am @tv42 and I approve of this message.

Well, except for one thing: LICENSE refers to AUTHORS, which does not exist.

**Comment by graingert** [comment]
@tv42 https://github.com/twisted/ldaptor/pull/208/files
