### ISSUE TITLE
Run LDAP Proxy example and get an error,  "cannot import name connectToLDAPEndpoint"

### ISSUE THREAD

**Issue by systex** [twisted/ldaptor#51]
Hello Sir, 

I followed LDAP Proxy examples of ldaptor on http://ldaptor.readthedocs.org/en/latest/cookbook/ldap-proxy.html. I get an error,   "cannot import name connectToLDAPEndpoint", both in ldaptor 14.0 and 0.43 at python 2.7.

Could you kindly check the example and guide me howto make LDAP Proxy code runs?

**Comment by cwaldbieser** [comment]
Are you using the latest ldaptor from github?  Those docs look like they
are from the latest source, not the latest release.

Thanks,
Carl

**Comment by systex** [comment]
Thank Carl! I'll download the source and test again.

**Comment by systex** [comment]
Great! It works like a charm. Thank Carl.

**Comment by psi29a** [comment]
I guess it is time to make another release? ;)

**Comment by systex** [comment]
Yeah, I look forward to getting it!
