### ISSUE TITLE
Allow BIND using UPN to fake a AD LDAP server.

### ISSUE THREAD

**Issue by adiroiban** [twisted/ldaptor#78]
Not sure if someone can find it useful.

Active Directory LDAP implementation allows to bind using UPN (user@domain.com) or down-level logon name (user\domain)

I am using ldaptor to support the testing for an ldap client code.

For some unit / integration tests for me is easier to use ldaptor, so I have created this modified server which allows to bind using something similar to an UPN 

Code is here

https://gist.github.com/adiroiban/cc60a78e0275e07869e3ed1fb0114621

If there is interest, I can look at pushing a PR... but the code is not designed for production :)

**Comment by cwaldbieser** [comment]
I'm not sure if it belongs in the code base-- but it might be interesting to put it in the [cookbook under servers.](http://ldaptor.readthedocs.io/en/latest/cookbook/servers.html) .  Could you write it up as a recipe?

**Comment by adiroiban** [comment]
Fixed in #79
